[package]
name = "kagc_mir_lowering"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
lazy_static = "1.4.0"

kagc_mir = { path = "../kagc_mir" }
kagc_lir = { path = "../kagc_lir" }